news_sites:
  eluniversal:
    url: https://eluniversal.com.mx
    search: /buscar/
    queries:
      search_article_links: '._new'
      homepage_article_links: '.field-content a'
      article_body: '.field-name-body'
      article_title: '.pane-content h1'
  elpais:
    url: https://elpais.com
    queries:
      homepage_article_links: '.headline a'
      article_body: '.article_body'
      article_title: '.a_hg h1'